spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/birthday
        username: root
        password: Yjt050927

  application:
    name: App